#!/bin/bash -e
# Retrieve information about dependencies of an external Maven artifact

TMPDIR=$(mktemp -d --tmpdir 'deps-XXXXXXXXXX')
trap "rm -r '$TMPDIR'" EXIT

MAVEN_OPTS=""
COORDS=()

while (( $# > 0 ))
do
        case "$1" in
                -*)
                        MAVEN_OPTS+=" $1"
                        ;;
		*)
			COORDS+=("$1")
			;;
	esac
	shift
done

echo 1>&2 "Downloading POMs to $TMPDIR"
for COORD in "${COORDS[@]}"
do
	echo 1>&2 "Downloading POM of $COORD"
	mvn -q $MAVEN_OPTS dependency:copy -Dartifact="$COORD:pom" -DoutputDirectory="$TMPDIR/$COORD/"
done

for COORD in "${COORDS[@]}"
do
	mvn org.apache.maven.plugins:maven-dependency-plugin:3.2.0:tree -f "$TMPDIR/$COORD"/*.pom -Dscope=runtime
done

