#!/bin/bash -e
# gh-issue-events: look for issue events of a given type on GitHub

function usage() {
	cat 1>&2 <<EOF
Usage:
    $0 <owner>/<repo> [event_type[,event_type...]][/event_subtype[,event_subtype...]] [cutoff]
Parameters:
	event_type: GitHub event type, see https://docs.github.com/en/rest/using-the-rest-api/github-event-types?apiVersion=2022-11-28
	event_subtype: GitHub event "subtype", e.g. 'closed', 'opened', etc.
	cutoff: date, ISO format (default 7 days ago)
EOF
}

function prop {
    grep "${1}" "${2}" | cut -d'=' -f2
}

if (( $# < 1 ))
then
	usage
	exit 1
fi
owner_repo=$1
shift

if (( $# > 0 ))
then
	type=$(echo "$1" | awk -F '/' '{ print $1 }')
	subtype=$(echo "$1" | awk -F '/' '{ print $2 }')

	[ -n "$type" ] || usage
  filter="select([.type] | inside([\"$(echo $type | sed 's/,/","/g')\"]))"

	if [ -n "$subtype" ]
	then
    filter="$filter | select([.payload.action] | inside([\"$(echo $subtype | sed 's/,/","/g')\"]))"
  fi

	shift
else
	filter="."
fi


if (( $# > 0 ))
then
	cutoff="$(date +%s -u -d "$1")"
	shift
else
	cutoff="$(date +%s -u -d '7 days ago')"
fi

if (( $# > 0 ))
then
	usage
	exit 1
fi

echo 1>&2 "Cutoff: $cutoff ($(date -Isecond -u -d @$cutoff)); filter: $filter"

ghtoken=$(prop 'oauth' $HOME/.github)

function fetch_page() {
  echo 1>&2 "Fetching page $1"
  curl --fail-with-body -s -S -G -X GET -L \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer $ghtoken" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    https://api.github.com/repos/$owner_repo/events \
    -d "page=$i" -d 'per_page=100' \
    | jq -r "[ .[] | select( (.created_at | fromdate) > $cutoff ) ] | if (length) > 0 then .[] else halt_error end"
}

i=1
while fetch_page $i
do
	((i+=1))
	echo 1>&2 "Fetching additional page $i..."
done | jq -s -r ".[] | $filter"
