#!/bin/bash -e
# Retrieve information about source code in one or more Maven projects

function list() {
	(( $# > 0 )) && dir="$1" && shift
	find $dir -path '*/src/main/java/*' -name '*.java' "$@"
}

function count() {
	for dir in "${@}"
	do
		echo -n "$dir: "
		list "$dir" -print0 \
			| wc --files0-from - -l | tail -1 | sed -s 's/ total$//'
	done
}

function blame() {
	for dir in "${@}"
	do
		echo "$dir: "
		list "$dir" -print0 \
			| xargs -0 --no-run-if-empty -n 1 git blame -M --line-porcelain -- | sed -n 's/^author //p' | sort | uniq -c | sort -rn

	done
}

function diff_api() {
	RANGE=$1
	shift
	declare -a DIRS
	DIRS=("${@}")
	(( $# == 0 )) && DIRS=(":*.java")
	tig log --cherry-pick --right-only $RANGE -- "${DIRS[@]}" ':!*/spi/*' ':!*/impl/*' ':!*/src/test/*'
}

function diff_spi() {
	RANGE=$1
	shift
	declare -a DIRS
	DIRS=("${@}")
	(( $# == 0 )) && DIRS=(":*/spi/*.java")
	tig log --cherry-pick --right-only $RANGE -- "${DIRS[@]}" ':!*/impl/*' ':!*/src/test/*'
}


FEATURE=count

while getopts 'clbd:' opt
do
	case "$opt" in
		c)
			FEATURE=count
			;;
		l)
			FEATURE=list
			;;
		b)
			FEATURE=blame
			;;
		d)
			case "$OPTARG" in
				"api")
					FEATURE="diff_api"
					;;
				"spi")
					FEATURE="diff_spi"
					;;
				*)
					echo 2>&1 "Unsupported diff mode: $OPTARG"
					exit 1
					;;
			esac
			;;
		\?)
			exit 1
			;;
	esac
done

shift $(( OPTIND - 1 ))

$FEATURE "$@"

