#!/bin/bash -e
# Retrieve information about source code in one or more Maven projects

function list() {
	(( $# > 0 )) && DIR="$1" && shift
	declare -a FILTERS
	case "$FILTER" in
		"api")
			FILTERS=(-path '*/src/main/*' -not -path "*/$INTERNAL_PACKAGE_MARKER/*" -not -path '*/spi/*')
			;;
		"spi")
			FILTERS=(-path '*/src/main/*' -path '*/spi/*' -not -path "*/$INTERNAL_PACKAGE_MARKER/*")
			;;
		"public")
			FILTERS=(-path '*/src/main/*' -not -path "*/$INTERNAL_PACKAGE_MARKER/*")
			;;
		"impl")
			FILTERS=(-path '*/src/main/*' -path "*/$INTERNAL_PACKAGE_MARKER/*" -not -path '*/spi/*')
			;;
		"main")
			FILTERS=(-path '*/src/main/*')
			;;
		"test")
			FILTERS=(-path '*/src/test/*')
			;;
		"all")
			FILTERS=('(' -path '*/src/main/*' -o -path '*/src/test/*' ')')
			;;
	esac
	set -o xtrace
	find $DIR -name '*.java' "${FILTERS[@]}" "$@"
	set +o xtrace
}

function count() {
	list "${@}" -print0 \
		| wc --files0-from - -l | tail -1 | sed -s 's/ total$//'
}

function git_blame() {
	for DIR in "${@}"
	do
		echo "$DIR: "
		list "$DIR" -print0 \
			| xargs -0 --no-run-if-empty -n 1 git blame -M --line-porcelain -- | sed -n 's/^author //p' | sort | uniq -c | sort -rn

	done
}

function git_history() {
	local RANGE=$1
	shift
	declare -a DIRS
	DIRS=("${@}")
	declare -a NEGATIVE_FILTERS
	case "$FILTER" in
		"api")
			(( $# != 0 )) || DIRS=(":*.java")
			NEGATIVE_FILTERS=(':!*/spi/*' ":!*/$INTERNAL_PACKAGE_MARKER/*" ':!*/src/test/*')
			;;
		"spi")
			(( $# != 0 )) || DIRS=(":*/spi/*.java")
			NEGATIVE_FILTERS=(":!*/$INTERNAL_PACKAGE_MARKER/*" ':!*/src/test/*')
			;;
		"public")
			(( $# != 0 )) || DIRS=(":*.java")
			NEGATIVE_FILTERS=(":!*/$INTERNAL_PACKAGE_MARKER/*" ':!*/src/test/*')
			;;
		"impl")
			(( $# != 0 )) || DIRS=(":*/$INTERNAL_PACKAGE_MARKER/*.java")
			NEGATIVE_FILTERS=(':!*/spi/*' ':!*/src/test/*')
			;;
		"main")
			(( $# != 0 )) || DIRS=(":*.java")
			NEGATIVE_FILTERS=(":!*/src/test/*")
			;;
		"test")
			(( $# != 0 )) || DIRS=(":*/src/test/*.java")
			NEGATIVE_FILTERS=()
			;;
		"all")
			(( $# != 0 )) || DIRS=(":*.java")
			NEGATIVE_FILTERS=()
			;;
	esac
	tig log --cherry-pick --right-only $RANGE -- "${DIRS[@]}" "${NEGATIVE_FILTERS[@]}"
}

function git_diff() {
	local RANGE=$1
	shift
	declare -a DIRS
	DIRS=("${@}")
	declare -a NEGATIVE_FILTERS
	case "$FILTER" in
		"api")
			(( $# != 0 )) || DIRS=(":*.java")
			NEGATIVE_FILTERS=(':!*/spi/*' ":!*/$INTERNAL_PACKAGE_MARKER/*" ':!*/src/test/*')
			;;
		"spi")
			(( $# != 0 )) || DIRS=(":*/spi/*.java")
			NEGATIVE_FILTERS=(":!*/$INTERNAL_PACKAGE_MARKER/*" ':!*/src/test/*')
			;;
		"public")
			(( $# != 0 )) || DIRS=(":*.java")
			NEGATIVE_FILTERS=(":!*/$INTERNAL_PACKAGE_MARKER/*" ':!*/src/test/*')
			;;
		"impl")
			(( $# != 0 )) || DIRS=(":*/$INTERNAL_PACKAGE_MARKER/*.java")
			NEGATIVE_FILTERS=(':!*/spi/*' ':!*/src/test/*')
			;;
		"main")
			(( $# != 0 )) || DIRS=(":*.java")
			NEGATIVE_FILTERS=(":!*/src/test/*")
			;;
		"test")
			(( $# != 0 )) || DIRS=(":*/src/test/*.java")
			NEGATIVE_FILTERS=()
			;;
		"all")
			(( $# != 0 )) || DIRS=(":*.java")
			NEGATIVE_FILTERS=()
			;;
	esac
	set -o xtrace
	git diff --patch-with-stat --cherry-pick --right-only $RANGE -- "${DIRS[@]}" "${NEGATIVE_FILTERS[@]}"
	set +o xtrace
}

FEATURE=count
FILTER=nontest
INTERNAL_PACKAGE_MARKER=impl

while getopts 'clbdhf:i:' opt
do
	case "$opt" in
		c)
			FEATURE=count
			;;
		l)
			FEATURE=list
			;;
		b)
			FEATURE=git_blame
			;;
		d)
			FEATURE=git_diff
			;;
		h)
			FEATURE=git_history
			;;
		f)
			case "$OPTARG" in
				"api"|"spi"|"public"|"impl"|"test"|"main"|"all")
					FILTER="$OPTARG"
					;;
				*)
					echo 2>&1 "Unrecognized source filter: $OPTARG"
					exit 1
					;;
			esac
			;;
		i)
			INTERNAL_PACKAGE_MARKER="$OPTARG"
			;;
		\?)
			exit 1
			;;
	esac
done

shift $(( OPTIND - 1 ))

$FEATURE "$@"

