#!/bin/bash -e
# Retrieve information about source code in one or more Maven projects

function list() {
	(( $# > 0 )) && DIR="$1" && shift
	declare -a TEST_FILTERS
	TEST_FILTERS=('(' -path '*/src/test/*')
 	for marker in "${TEST_MARKERS[@]}"
	do
		TEST_FILTERS+=(-o -path "$marker/*" -o -path "*/$marker/*")
	done
	TEST_FILTERS+=(')')
	declare -a IMPL_FILTERS
	IMPL_FILTERS=('(' -path '*/src/main/*' '(' '-false')
 	for marker in "${INTERNAL_PACKAGE_MARKERS[@]}"
	do
		IMPL_FILTERS+=(-o -path "*/$marker/*")
	done
	IMPL_FILTERS+=(')' ')')
	declare -a SPI_FILTERS
	SPI_FILTERS=('(' -path '*/spi/*' ')')

	declare -a FILTERS
	FILTERS=()
	case "$FILTER" in
		"api")
			FILTERS=(-path '*/src/main/*' -not "${IMPL_FILTERS[@]}" -not "${SPI_FILTERS[@]}" -not "${TEST_FILTERS[@]}")
			;;
		"spi")
			FILTERS=(${SPI_FILTERS[@]} -not "${TEST_FILTERS[@]}")
			;;
		"public")
			FILTERS=(-path '*/src/main/*' -not "${IMPL_FILTERS[@]}" -not "${TEST_FILTERS[@]}")
			;;
		"impl")
			FILTERS=("${IMPL_FILTERS[@]}" -not "${TEST_FILTERS[@]}")
			;;
		"main")
			FILTERS=(-path '*/src/main/*' -not "${TEST_FILTERS[@]}")
			;;
		"test")
			FILTERS=("${TEST_FILTERS[@]}")
			;;
		"all")
			FILTERS=()
			;;
	esac
	set -o xtrace
	find $DIR -name '*.java' "${FILTERS[@]}" "$@"
	set +o xtrace
}

function count() {
	list "${@}" -print0 \
		| wc --files0-from - -l | tail -1 | sed -s 's/ total$//'
}

function git_blame() {
	for DIR in "${@}"
	do
		echo "$DIR: "
		list "$DIR" -print0 \
			| xargs -0 --no-run-if-empty -n 1 git blame -M --line-porcelain -- | sed -n 's/^author //p' | sort | uniq -c | sort -rn

	done
}

function git_history() {
	local RANGE=$1
	shift
	tig log --cherry-pick --right-only $RANGE -- $(git_filters "$@")
}

function git_diff() {
	local RANGE=$1
	shift
	set -o xtrace
	git diff --patch-with-stat --cherry-pick --right-only $RANGE -- $(git_filters "$@")
	set +o xtrace
}

function git_filters() {
	declare -a DIRS
	DIRS=("${@}")
	declare -a NEGATIVE_FILTERS

	declare -a NOT_TEST_FILTERS
	NOT_TEST_FILTERS=(':!*/src/test/*')
	for marker in "${TEST_MARKERS[@]}"
	do
		NOT_TEST_FILTERS+=(":!$marker/*" ":!*/$marker/*")
	done
	declare -a NOT_IMPL_FILTERS
	NOT_IMPL_FILTERS=()
	for marker in "${INTERNAL_PACKAGE_MARKERS[@]}"
	do
		NOT_IMPL_FILTERS+=(":!*/$marker/*")
	done
	declare -a NOT_SPI_FILTERS
	NOT_SPI_FILTERS=(':!*/spi/*')

	case "$FILTER" in
		"api")
			(( $# != 0 )) || DIRS=(":*.java")
			NEGATIVE_FILTERS=("${NOT_SPI_FILTERS[@]}" "${NOT_IMPL_FILTERS[@]}" "${NOT_TEST_FILTERS[@]}")
			;;
		"spi")
			(( $# != 0 )) || DIRS=(":*/spi/*.java")
			NEGATIVE_FILTERS=("${NOT_IMPL_FILTERS[@]}" "${NOT_TEST_FILTERS[@]}")
			;;
		"public")
			(( $# != 0 )) || DIRS=(":*.java")
			NEGATIVE_FILTERS=("${NOT_IMPL_FILTERS[@]}" "${NOT_TEST_FILTERS[@]}")
			;;
		"impl")
			(( $# != 0 )) || DIRS=(":*/$INTERNAL_PACKAGE_MARKER/*.java")
			NEGATIVE_FILTERS=("${NOT_SPI_FILTERS[@]}" "${NOT_TEST_FILTERS[@]}")
			;;
		"main")
			(( $# != 0 )) || DIRS=(":*.java")
			NEGATIVE_FILTERS=("${NOT_TEST_FILTERS[@]}")
			;;
		"test")
			(( $# != 0 )) || DIRS=(":*/src/test/*.java" ":$INTEGRATION_TEST_MARKER/*" ":*/$INTEGRATION_TEST_MARKER/*")
			NEGATIVE_FILTERS=()
			;;
		"all")
			(( $# != 0 )) || DIRS=(":*.java")
			NEGATIVE_FILTERS=()
			;;
	esac
	echo "${DIRS[@]}" "${NEGATIVE_FILTERS[@]}"
}


FEATURE=count
FILTER=nontest
declare -a INTERNAL_PACKAGE_MARKER
INTERNAL_PACKAGE_MARKER=()
declare -a TEST_MARKERS
TEST_MARKERS=()

while getopts 'clbdhf:i:t:' opt
do
	case "$opt" in
		c)
			FEATURE=count
			;;
		l)
			FEATURE=list
			;;
		b)
			FEATURE=git_blame
			;;
		d)
			FEATURE=git_diff
			;;
		h)
			FEATURE=git_history
			;;
		f)
			case "$OPTARG" in
				"api"|"spi"|"public"|"impl"|"test"|"main"|"all")
					FILTER="$OPTARG"
					;;
				*)
					echo 2>&1 "Unrecognized source filter: $OPTARG"
					exit 1
					;;
			esac
			;;
		i)
			INTERNAL_PACKAGE_MARKERS+=("$OPTARG")
			;;
		t)
			TEST_MARKERS+=("$OPTARG")
			;;
		\?)
			exit 1
			;;
	esac
done

if (( ${#INTERNAL_PACKAGE_MARKERS[@]} == 0 ))
then
	INTERNAL_PACKAGE_MARKERS+=(impl internal checkstyle)
fi

if (( ${#TEST_MARKERS[@]} == 0 ))
then
	TEST_MARKERS+=('test' tests integrationtest integrationtests integration-test integration-tests)
fi

shift $(( OPTIND - 1 ))

$FEATURE "$@"

