#!/bin/bash -e

ARG=$1
shift

HOME_VARIABLE_NAME="GRAALVM${ARG}_HOME"
PREFIXED_PATH="${HOME}/tools/java/graalvm${ARG}"

NEW_HOME="${ARG}"
if ! [ -e "$NEW_HOME" ]
then
        NEW_HOME="${PREFIXED_PATH}"
fi
if ! [ -e "$NEW_HOME" ]
then
	NEW_HOME=$(eval "echo \$${HOME_VARIABLE_NAME}")
fi
if ! [ -e "$NEW_HOME" ]
then
	echo 1>&2 "Cannot find the GraalVM install for '$ARG': '$ARG' is not a valid path, nor is '$PREFIXED_PATH', and environment variable '$HOME_VARIABLE_NAME' is not defined."
	exit 1
fi

echo 1>&2 "Graalvm Home: $NEW_HOME"
export JAVA_HOME="$NEW_HOME"
export GRAALVM_HOME="$NEW_HOME"
export PATH="$NEW_HOME/bin:$PATH"
java -version 1>&2

exec $*

