#!/bin/bash -e

ARG=$1
shift

HOME_VARIABLE_NAME="JAVA${ARG}_HOME"
NEW_HOME=$(eval "echo \$${HOME_VARIABLE_NAME}")

if ! [ -e "$NEW_HOME" ]
then
	NEW_HOME="${ARG}"
fi
if ! [ -e "$NEW_HOME" ]
then
	echo 1>&2 "Cannot find the JDK for '$ARG': environment variable '$HOME_VARIABLE_NAME' is not defined, and '$ARG' is not a valid path."
	exit 1
fi

echo 1>&2 "Java Home: $NEW_HOME"
export JAVA_HOME="$NEW_HOME"
export PATH="$NEW_HOME/bin:$PATH"
java -version 1>&2

exec $*

