#!/bin/bash -e

ARG=$1
shift

HOME_VARIABLE_NAME="JAVA${ARG}_HOME"
PREFIXED_PATH="${HOME}/tools/java/jdk${ARG}"

NEW_HOME="${ARG}"
if ! [ -e "$NEW_HOME" ]
then
        NEW_HOME="${PREFIXED_PATH}"
fi
if ! [ -e "$NEW_HOME" ]
then
        NEW_HOME=$(eval "echo \$${HOME_VARIABLE_NAME}")
fi
if ! [ -e "$NEW_HOME" ]
then
        echo 1>&2 "Cannot find the JDK install for '$ARG': '$ARG' is not a valid path, nor is '$PREFIXED_PATH', and environment variable '$HOME_VARIABLE_NAME' is not defined."
        exit 1
fi

echo 1>&2 "Java Home: $NEW_HOME"
export JAVA_HOME="$NEW_HOME"
export PATH="$NEW_HOME/bin:$PATH"
java -version 1>&2

exec $*

