#!/bin/bash -e

VERSION=$1
shift

HOME_VARIABLE_NAME="JAVA${VERSION}_HOME"
NEW_HOME=$(eval "echo \$${HOME_VARIABLE_NAME}")

if ! [ -e "$NEW_HOME" ]
then
	echo 1>&2 "Unsupported java version: '$VERSION'. Is '$HOME_VARIABLE_NAME' defined?"
	exit 1
fi

echo 1>&2 "Java Home: $NEW_HOME"
export JAVA_HOME="$NEW_HOME"
export PATH="$NEW_HOME/bin:$PATH"
java -version 1>&2

exec $*

